### ISSUE TITLE
npm ERR! Udeler@1.6.2 build-win: `electron-builder -w`

### ISSUE THREAD

**Issue by EgyptianM** [FaisalUmair/udemy-downloader-gui#168]
Assalamu Alykom

I get this error when I try to build it on Windows 7

`npm ERR! Udeler@1.6.2 build-win: `electron-builder -w` 
`

![image](https://user-images.githubusercontent.com/12565380/45759982-6b057180-bc29-11e8-98e4-dec2488a6d23.png)

**Comment by EgyptianM** [comment]
Thank you for your reply @FaisalUmair 
I installed electron-builder but I had another error 


```
C:\Users\Mohammad\AppData\Roaming\npm\node_modules\electron-builder\out\cli\cli.js:5
  const data = require("bluebird-lst");
  ^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

npm ERR! Udeler@1.6.2 build-win: `electron-builder -w`
npm ERR! Exit status 8
```


![image](https://user-images.githubusercontent.com/12565380/45914377-b21b7e80-be44-11e8-9ade-8d88d97c11b5.png)

**Comment by EgyptianM** [comment]
Updating Node.js solved the issue.
Thank you.

Is it available to run it as a web page?

**Comment by FaisalUmair** [comment]
Yeah, updating NodeJS was required. And you can't run the exact same application in a normal web browser. But I have a web version which provides download links for downloading specific lectures or the entire course using a third party download manager. Check [Udeler Web](https://www.udeler.com)

**Comment by EgyptianM** [comment]
Is it on GitHub too or you provide the source code?

في سبت، ٢٢ سبتمبر، ٢٠١٨ ٦:٠٨ م Faisal Umair <notifications@github.com> كتب:

**Comment by FaisalUmair** [comment]
No, the source code is not available.
